Reading random file (null)
spliting files...
Reading random file random.txt
normal_operator_size = 4
normal operator run count = 2
critical_operator_size = 3
critical_operator run count = 2
[33mYou are running in a fuzzing environment[0m
[1;31mrunning test case 2[0m
start nodes....
node 0 start command is : java -cp /home/zyh/zookeeper/lib/*:/home/zyh/zookeeper/conf org.apache.zookeeper.server.quorum.QuorumPeerMain zoo1
node 1 start command is : java -cp /home/zyh/zookeeper/lib/*:/home/zyh/zookeeper/conf org.apache.zookeeper.server.quorum.QuorumPeerMain zoo2
node 2 start command is : java -cp /home/zyh/zookeeper/lib/*:/home/zyh/zookeeper/conf org.apache.zookeeper.server.quorum.QuorumPeerMain zoo3
node 3 start command is : java -cp /home/zyh/zookeeper/lib/*:/home/zyh/zookeeper/conf org.apache.zookeeper.server.quorum.QuorumPeerMain zoo4
node 4 start command is : java -cp /home/zyh/zookeeper/lib/*:/home/zyh/zookeeper/conf org.apache.zookeeper.server.quorum.QuorumPeerMain zoo5
Run init operator
Connecting to 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
Created /a
running operator ZooKeeperGet
timeout 3 /usr/share/zookeeper/bin/zkCli.sh -server 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185 get /a
Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /a
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1212)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1241)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:725)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:599)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:362)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:290)
running operator ZooKeeperSetWithVersion
timeout 3 /usr/share/zookeeper/bin/zkCli.sh -server 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185 set /a 2351664357 2
Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /a
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.setData(ZooKeeper.java:1327)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:717)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:599)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:362)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:290)
running operator RandomStart
all nodes are alive.
running operator ZooKeeperSet
timeout 3 /usr/share/zookeeper/bin/zkCli.sh -server 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185 set /a 78640001
client operator got timeout
running operator ZooKeeperSet
timeout 3 /usr/share/zookeeper/bin/zkCli.sh -server 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185 set /a 3860652058
cZxid = 0x100000002
ctime = Mon Nov 01 10:55:36 CST 2021
mZxid = 0x200000002
mtime = Mon Nov 01 10:55:41 CST 2021
pZxid = 0x100000002
cversion = 0
dataVersion = 1
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 10
numChildren = 0
Connecting to 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185
running operator RandomStart
all nodes are alive.
running operator ZooKeeperGet
timeout 3 /usr/share/zookeeper/bin/zkCli.sh -server 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185 get /a
cZxid = 0x100000002
ctime = Mon Nov 01 10:55:36 CST 2021
mZxid = 0x200000002
mtime = Mon Nov 01 10:55:41 CST 2021
pZxid = 0x100000002
cversion = 0
dataVersion = 1
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 10
numChildren = 0
Connecting to 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
3860652058
running operator ZooKeeperSet
timeout 3 /usr/share/zookeeper/bin/zkCli.sh -server 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185 set /a 1412657682
cZxid = 0x100000002
ctime = Mon Nov 01 10:55:36 CST 2021
mZxid = 0x200000007
mtime = Mon Nov 01 10:55:42 CST 2021
pZxid = 0x100000002
cversion = 0
dataVersion = 2
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 10
numChildren = 0
Connecting to 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185
node 3 is terminiated normally.
check failed!
The remaining alive node count is 5
Fuzzing is stopped, now we wait for 3 seconds and then run some normal operators to see whether it works as usual.
running operator ZooKeeperSetWithVersion
timeout 3 /usr/share/zookeeper/bin/zkCli.sh -server 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185 set /a 126292416 1
Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /a
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.setData(ZooKeeper.java:1327)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:717)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:599)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:362)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:290)
running operator ZooKeeperSetWithVersion failed after fuzzing
running operator ZooKeeperGet
timeout 3 /usr/share/zookeeper/bin/zkCli.sh -server 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185 get /a
cZxid = 0x100000002
ctime = Mon Nov 01 10:55:36 CST 2021
mZxid = 0x200000007
mtime = Mon Nov 01 10:55:42 CST 2021
pZxid = 0x100000002
cversion = 0
dataVersion = 2
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 10
numChildren = 0
Connecting to 127.0.1.1:2181,127.0.1.1:2182,127.0.1.1:2183,127.0.1.1:2184,127.0.1.1:2185

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
1412657682
stopping...

Usage:
 kill [options] <pid> [...]

Options:
 <pid> [...]            send signal to every <pid> listed
 -<signal>, -s, --signal <signal>
                        specify the <signal> to be sent
 -l, --list=[<signal>]  list all signal names, or convert one to a name
 -L, --table            list all signal names in a nice table

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).
backup test cases
/home/zyh/distributed-system-test/zookeeper_test/bin
3
./test_cases/2/log_app_1_0:2021-11-01 10:55:42,309 [myid:2] - ERROR [SyncThread:2:ZooKeeperCriticalThread@49] - Severe unrecoverable error, from thread : SyncThread:2
./test_cases/2/log_app_3_0:2021-11-01 10:55:41,215 [myid:4] - ERROR [SyncThread:4:ZooKeeperCriticalThread@49] - Severe unrecoverable error, from thread : SyncThread:4
./test_cases/2/log_app_3_0:2021-11-01 10:55:41,247 [myid:4] - ERROR [SyncThread:4:ZooKeeperCriticalThread@49] - Severe unrecoverable error, from thread : SyncThread:4
./test_cases/2/log_app_3_0:2021-11-01 10:55:41,271 [myid:4] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 0
./test_cases/2/log_app_4_0:2021-11-01 10:55:37,476 [myid:5] - ERROR [SyncThread:5:ZooKeeperCriticalThread@49] - Severe unrecoverable error, from thread : SyncThread:5
./test_cases/2/log_app_4_0:2021-11-01 10:55:37,507 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52818:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:37,508 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52814:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:37,509 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52820:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:37,510 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52816:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:41,220 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52832:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:41,245 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52850:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:41,255 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52852:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:41,269 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52854:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:42,312 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52834:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:46,546 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52838:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:46,559 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52864:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
./test_cases/2/log_app_4_0:2021-11-01 10:55:46,570 [myid:5] - ERROR [LearnerHandler-/127.0.0.1:52830:LearnerHandler@715] - Unexpected exception in LearnerHandler: 
grep: input file â€˜./test_cases/2/log_testâ€™ is also the output
Find check failed!
